// Generated by crates/app. Do not edit; run `cargo run -p mdreader-app --bin export-bindings`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Read a document from disk and return its content and metadata. */
	openDocument: (path: string) => typedError<Document, Error>(__TAURI_INVOKE("open_document", { path })),
	/**
	 *  Save the buffer in the file's stored form, refusing when the file on
	 *  disk no longer matches `expected_hash`.
	 */
	saveDocument: (path: string, content: string, expectedHash: string | null, format: FileFormat) => typedError<SaveResult, Error>(__TAURI_INVOKE("save_document", { path, content, expectedHash, format })),
	/**  Rewrite a non-UTF-8 file as UTF-8 and return it freshly read. */
	convertDocumentToUtf8: (path: string) => typedError<Document, Error>(__TAURI_INVOKE("convert_document_to_utf8", { path })),
	/**
	 *  Let the webview load images from a document's folder and below.
	 * 
	 *  The asset protocol starts with an empty scope (design 8), and it grows
	 *  only here, only to the folder of a file the reader has opened. Nothing
	 *  else in the app can widen it, and nothing outside those folders is
	 *  reachable from the page.
	 */
	allowDocumentImages: (path: string) => typedError<null, Error>(__TAURI_INVOKE("allow_document_images", { path })),
	/**
	 *  Store an image pasted into a document, beside it in `assets`.
	 * 
	 *  The bytes arrive base64-encoded because that is one string across the
	 *  bridge; the alternative the generated bindings would give us is a JSON
	 *  array of a million numbers for every screenshot.
	 */
	writeAsset: (document: string, name: string, data: string) => typedError<AssetWrite, Error>(__TAURI_INVOKE("write_asset", { document, name, data })),
	/**
	 *  Store an image dropped onto a document. The same gesture, arriving as
	 *  a path rather than as bytes, so the file is copied and never crosses
	 *  the bridge at all.
	 */
	importAsset: (document: string, source: string) => typedError<AssetWrite, Error>(__TAURI_INVOKE("import_asset", { document, source })),
	/**  Watch a file for writes by other processes. */
	watch: (path: string) => typedError<null, Error>(__TAURI_INVOKE("watch", { path })),
	/**  Stop watching a file. */
	unwatch: (path: string) => typedError<null, Error>(__TAURI_INVOKE("unwatch", { path })),
	/**
	 *  Three-way merge of an external write into a dirty buffer (design 7.2).
	 * 
	 *  The one command with no failure to report: three strings always have
	 *  a merge, even when every hunk of it is a conflict.
	 */
	merge3: (base: string, ours: string, theirs: string) => __TAURI_INVOKE<MergeResult>("merge3", { base, ours, theirs }),
	/**  Store a snapshot of `content` for `path`. */
	snapshot: (path: string, content: string, author: SnapshotAuthor) => typedError<SnapshotInfo, Error>(__TAURI_INVOKE("snapshot", { path, content, author })),
	/**  List the snapshots stored for `path`, newest first. */
	listSnapshots: (path: string) => typedError<SnapshotInfo[], Error>(__TAURI_INVOKE("list_snapshots", { path })),
	/**  Read one snapshot's content. */
	readSnapshot: (id: string) => typedError<string, Error>(__TAURI_INVOKE("read_snapshot", { id })),
	/**
	 *  What this window looked like when it was last open, plus the
	 *  preferences and the recent files (design 4.1).
	 * 
	 *  One round trip, because a window needs all three before it draws.
	 */
	loadWindow: () => __TAURI_INVOKE<Restore>("load_window"),
	/**
	 *  Record what this window holds.
	 * 
	 *  This is both halves of design 6.5: what the next launch puts back,
	 *  and the registry that decides which window a file the OS hands us
	 *  belongs to. The value is current the moment this returns; only the
	 *  write to disk waits for the store's interval.
	 */
	saveWindow: (content: WindowContent, recents: string[]) => __TAURI_INVOKE<void>("save_window", { content, recents }),
	/**  Change the preferences. */
	saveSettings: (settings: Settings) => __TAURI_INVOKE<void>("save_settings", { settings }),
	/**
	 *  Write the settings and the session now, rather than at the next
	 *  interval. What a window does before it closes.
	 */
	flushState: () => typedError<null, Error>(__TAURI_INVOKE("flush_state")),
	/**
	 *  Files the OS asked this window to open before it was listening.
	 * 
	 *  Draining the queue is also how a window says it is ready: from here
	 *  on the same files arrive as an event instead of waiting, which is
	 *  what keeps a launch argument from being lost to a listener that was
	 *  not attached yet, and from being opened twice by one that was.
	 */
	takeLaunchPaths: () => __TAURI_INVOKE<string[]>("take_launch_paths"),
	/**  The window has finished what it wanted to do before closing. */
	confirmClose: () => __TAURI_INVOKE<void>("confirm_close"),
	/**
	 *  Align two block lists for the semantic diff (design 7.3, plan WP 2.2).
	 * 
	 *  The frontend sends the middle: the blocks the two sides already agree
	 *  on at each end are matched off there, where the saving is in what
	 *  never crosses the bridge.
	 * 
	 *  It cannot fail. Both sides arrive as arguments, so there is nothing
	 *  to read, nothing to lock, and no answer but the alignment of what
	 *  was sent.
	 */
	blockDiff: (oldBlocks: Block[], newBlocks: Block[]) => __TAURI_INVOKE<BlockOp[]>("block_diff", { oldBlocks, newBlocks }),
	/**  List a directory, honouring `.gitignore` (WP 2.x). */
	listDir: (path: string) => typedError<DirEntry[], Error>(__TAURI_INVOKE("list_dir", { path })),
	/**  Search file contents under `root` (WP 2.x). */
	search: (root: string, query: string, options: SearchOptions) => typedError<SearchHit[], Error>(__TAURI_INVOKE("search", { root, query, options })),
};

/** Events */
export const events = {
	beforeCloseEvent: makeEvent<BeforeCloseEvent>("before-close-event"),
	externalChangeEvent: makeEvent<ExternalChangeEvent>("external-change-event"),
	fileRemovedEvent: makeEvent<FileRemovedEvent>("file-removed-event"),
	fileRenamedEvent: makeEvent<FileRenamedEvent>("file-renamed-event"),
	openPathsEvent: makeEvent<OpenPathsEvent>("open-paths-event"),
};

/* Types */
/**  Whether the window follows the system or was told which to be. */
export type Appearance = "system" | "light" | "dark";

/**  A stored image: where it landed, and the link the document gets. */
export type AssetWrite = {
	path: string,
	/**
	 *  Relative to the document's folder, with forward slashes, ready to
	 *  go between the parentheses of a markdown link.
	 */
	relative: string,
	/**  False when the bytes were already there under this name. */
	written: boolean,
};

/**
 *  The window is about to close. Write down whatever is not on disk yet,
 *  then call `confirm_close`.
 */
export type BeforeCloseEvent = {
	label: string,
};

/**  A leaf block as the frontend flattens it (design 7.3). */
export type Block = {
	kind: string,
	text: string,
	from: number,
	to: number,
};

/**
 *  One step of the alignment of two block lists (design 7.3).
 * 
 *  The whole alignment is returned, `Equal` included, because that is
 *  what makes it an alignment: a consumer can walk both sides in step
 *  and knows what became of every block. `old` and `new` are indices
 *  into the lists that were sent, which carry the source ranges.
 * 
 *  A block that moved is reported once, where it arrived. Reporting the
 *  place it left as a deletion as well would mark the reader's document
 *  in two places for one thing having happened.
 */
export type BlockOp = { op: "equal"; old: number; new: number } | { op: "changed"; old: number; new: number; words: WordRun[] } | { op: "moved"; old: number; new: number } | { op: "inserted"; new: number } | { op: "deleted"; old: number };

/**  A hunk both sides changed, for the frontend to render as a conflict. */
export type Conflict = {
	from: number,
	to: number,
	ours: string,
	theirs: string,
};

/**  A selection, in UTF-16 offsets like every other position on the IPC. */
export type Cursor = {
	anchor: number,
	head: number,
};

export type DirEntry = {
	path: string,
	name: string,
	is_dir: boolean,
	byte_len: number,
	modified_ms: number | null,
};

/**  A document as read from disk. */
export type Document = {
	/**
	 *  The decoded content. For UTF-8 files this is the file's bytes minus the
	 *  BOM, with line endings untouched; the editor normalizes them itself.
	 */
	content: string,
	meta: DocumentMeta,
};

/**  Metadata about a document on disk. */
export type DocumentMeta = {
	path: string,
	/**  Size on disk in bytes. */
	byte_len: number,
	/**
	 *  Last modification time in milliseconds since the Unix epoch, when the
	 *  filesystem reports one.
	 */
	modified_ms: number | null,
	/**  BLAKE3 of the bytes on disk, hex. The token a save must present. */
	hash: string,
	/**
	 *  True for a file that is not UTF-8: it was decoded for display and
	 *  cannot be saved until converted.
	 */
	read_only: boolean,
	format: FileFormat,
};

/**
 *  One open document. Exactly one of the two fields is set: a file is
 *  read again from disk on restore, an untitled document is carried in
 *  the session file because losing it would lose the only copy.
 */
export type DocumentState = {
	path?: string | null,
	untitled?: Untitled | null,
};

/**  One line ending style. */
export type Eol = "lf" | "crlf" | "cr";

/**  Errors, serializable so the frontend can branch on `kind`. */
export type Error = { kind: "not_implemented"; command: string } | { kind: "read"; path: string; message: string } | { kind: "write"; path: string; message: string } | { kind: "hash_mismatch"; path: string; expected: string; actual: string } | { kind: "read_only_encoding"; path: string; encoding: string } | { kind: "unavailable"; what: string; message: string };

/**  Payload of the `external_change` event (design 6.4). */
export type ExternalChange = {
	path: string,
	content: string,
	hash: string,
	/**
	 *  Edits from the file as the watcher last read it to `content`.
	 * 
	 *  The shell does not apply these: it merges against its own base,
	 *  because a buffer and the file it was saved to are not always the
	 *  same string — saving restores the stored form, and a document
	 *  whose last newline the reader deleted sits on disk with one.
	 *  They are here for a writer that holds both sides itself, which is
	 *  the MCP path of Phase 3 (design 9).
	 */
	changes: PositionEdit[],
};

/**  The watcher's report of a write by another process (design 6.4). */
export type ExternalChangeEvent = ExternalChange;

/**  Which of the three bundled families the page is set in. */
export type Family = "sans" | "serif" | "mono";

/**
 *  How a file is stored, so a save can restore it. Returned on open and
 *  passed back on save; the app may change fields the user asked to change.
 */
export type FileFormat = {
	/**  Dominant line ending, used for new lines. */
	eol: Eol,
	/**  True when the file mixes endings; existing lines keep theirs on save. */
	mixed_eol: boolean,
	bom: boolean,
	/**  True when the file ended with a line terminator. */
	trailing_newline: boolean,
	/**  Encoding label from `encoding_rs`; only `utf-8` documents can be saved. */
	encoding: string,
};

/**
 *  Payload of the `file_removed` event: a file with a tab open on it is
 *  no longer on disk. The buffer stays; the next save recreates the file.
 */
export type FileRemoved = {
	path: string,
};

/**  A watched file is no longer on disk. */
export type FileRemovedEvent = FileRemoved;

/**
 *  Payload of the `file_renamed` event: the document is the same, its
 *  name is not, so the tab follows it.
 */
export type FileRenamed = {
	from: string,
	to: string,
};

/**  A watched file was renamed. */
export type FileRenamedEvent = FileRenamed;

export type MergeResult = {
	changes: PositionEdit[],
	conflicts: Conflict[],
};

/**
 *  Files the OS wants this window to open: a second launch, a Finder
 *  double-click, an `open` from a terminal.
 */
export type OpenPathsEvent = string[];

/**
 *  The page's own background (design 11), which is a setting of its own
 *  rather than a consequence of light or dark: paper colour changes
 *  reading comfort more than most people expect.
 */
export type Paper = "white" | "cream" | 
/**  A yellow legal pad. */
"pad" | 
/**  The high-contrast one, dark in a light window as well as a dark. */
"black";

/**  One position-based edit the frontend applies as a `CodeMirror` change. */
export type PositionEdit = {
	/**  UTF-16 offsets into the document the edit applies to. */
	from: number,
	to: number,
	insert: string,
};

/**
 *  What a window asks for when it starts.
 * 
 *  One round trip: the tabs it had, the files it has been opening, and
 *  the preferences, all of which it needs before it draws anything.
 */
export type Restore = {
	/**
	 *  `None` on a first launch, and after a session file that would not
	 *  parse: both mean a window with nothing to put back.
	 */
	content: WindowContent | null,
	recents: string[],
	settings: Settings,
};

/**  What a successful save reports back. */
export type SaveResult = {
	hash: string,
	byte_len: number,
	modified_ms: number | null,
};

export type SearchHit = {
	path: string,
	line: number,
	from: number,
	to: number,
	text: string,
};

export type SearchOptions = {
	case_sensitive: boolean,
	regex: boolean,
	max_results: number,
};

/**  Preferences that outlive every window (design 11, design 6.6). */
export type Settings = {
	/**
	 *  Design 6.6: on, because the file on disk is the channel to the AI
	 *  and an unsaved buffer is a state the AI cannot see.
	 */
	autosave?: boolean,
	appearance?: Appearance,
	paper?: Paper,
	family?: Family,
	/**  Reading size in CSS pixels; one of [`SIZES`]. */
	size?: number,
	/**  Line length in characters, within [`MEASURE_RANGE`]. */
	measure?: number,
};

/**
 *  Which of the sidebar's panels was showing (design 4.1, 4.4). The
 *  folder tree joins these in WP 2.4.
 */
export type SidebarPanel = "outline" | "history";

/**
 *  Who wrote a snapshot.
 * 
 *  `Autosave` is separate from `User` because it is the one author that
 *  writes on a timer rather than because somebody decided to: the history
 *  coalesces a run of those into one version, and never coalesces onto a
 *  version anybody asked for (design 6.6).
 */
export type SnapshotAuthor = "user" | "autosave" | "external" | "agent";

export type SnapshotInfo = {
	id: string,
	path: string,
	author: SnapshotAuthor,
	timestamp_ms: number,
	hash: string,
	byte_len: number,
};

/**
 *  What a tab is showing. Settings open as a tab rather than a modal
 *  (plan WP 1.9), so not every tab has a document behind it.
 */
export type TabKind = "document" | "settings";

/**  Which projection of a document a tab was showing (design 4.2). */
export type TabMode = "read" | "edit" | "source";

/**
 *  One tab: a view onto a document, with the state that is per view
 *  (design 6.5).
 */
export type TabState = {
	kind?: TabKind,
	/**
	 *  Index into the window's `documents`. Two tabs naming the same one
	 *  restore as two views of one buffer, sharing undo.
	 */
	document?: number,
	mode?: TabMode,
	pinned?: boolean,
	/**  The tab that was in front. The first one marked wins. */
	active?: boolean,
	selection?: Cursor,
	/**
	 *  Where the view was scrolled, as a source offset. A character
	 *  survives a change of window width; a pixel offset does not.
	 */
	anchor?: number,
	/**  Heading ids folded in Read mode. */
	folded?: string[],
};

/**  An untitled document: a buffer with nowhere else to be kept. */
export type Untitled = {
	name: string,
	text: string,
};

/**
 *  What a window's own webview knows about itself. The frontend owns
 *  every field; the label and the frame are the window manager's.
 */
export type WindowContent = {
	documents?: DocumentState[],
	tabs?: TabState[],
	sidebar?: boolean,
	/**  Which panel the sidebar was showing (design 4.4). */
	panel?: SidebarPanel,
	/**  Whether Read mode was showing the comments it folds away (4.3). */
	comments?: boolean,
};

/**
 *  A run of words that differ inside a pair of blocks the diff matched
 *  (design 7.3 step 3), as offsets into each side's block text.
 * 
 *  The offsets are into the block's text and not into the document,
 *  because the text is the normalized form: the words of a rewrapped
 *  paragraph are in different places in the file and the same places in
 *  what it says. Reverting is a block at a time, which is what the
 *  block's own range is for.
 * 
 *  One side is empty where the run is only an insertion or only a
 *  deletion, and sits where the missing words would go.
 */
export type WordRun = {
	old_from: number,
	old_to: number,
	new_from: number,
	new_to: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

