// Generated by crates/app. Do not edit; run `cargo run -p mdreader-app --bin export-bindings`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Read a document from disk and return its content and metadata. */
	openDocument: (path: string) => typedError<Document, Error>(__TAURI_INVOKE("open_document", { path })),
	/**
	 *  Save the buffer in the file's stored form, refusing when the file on
	 *  disk no longer matches `expected_hash`.
	 */
	saveDocument: (path: string, content: string, expectedHash: string | null, format: FileFormat) => typedError<SaveResult, Error>(__TAURI_INVOKE("save_document", { path, content, expectedHash, format })),
	/**  Rewrite a non-UTF-8 file as UTF-8 and return it freshly read. */
	convertDocumentToUtf8: (path: string) => typedError<Document, Error>(__TAURI_INVOKE("convert_document_to_utf8", { path })),
	/**  Start watching a file for external writes (WP 1.7). */
	watch: (path: string) => typedError<null, Error>(__TAURI_INVOKE("watch", { path })),
	/**  Stop watching a file (WP 1.7). */
	unwatch: (path: string) => typedError<null, Error>(__TAURI_INVOKE("unwatch", { path })),
	/**  Three-way merge of an external write into a dirty buffer (WP 1.7). */
	merge3: (base: string, ours: string, theirs: string) => typedError<MergeResult, Error>(__TAURI_INVOKE("merge3", { base, ours, theirs })),
	/**  Store a snapshot of `content` for `path` (WP 1.7). */
	snapshot: (path: string, content: string, author: SnapshotAuthor) => typedError<SnapshotInfo, Error>(__TAURI_INVOKE("snapshot", { path, content, author })),
	/**  List the snapshots stored for `path` (WP 1.7). */
	listSnapshots: (path: string) => typedError<SnapshotInfo[], Error>(__TAURI_INVOKE("list_snapshots", { path })),
	/**  Read one snapshot's content (WP 1.7). */
	readSnapshot: (id: string) => typedError<string, Error>(__TAURI_INVOKE("read_snapshot", { id })),
	/**  Align two block lists for the semantic diff (WP 2.x). */
	blockDiff: (oldBlocks: Block[], newBlocks: Block[]) => typedError<BlockOp[], Error>(__TAURI_INVOKE("block_diff", { oldBlocks, newBlocks })),
	/**  List a directory, honouring `.gitignore` (WP 2.x). */
	listDir: (path: string) => typedError<DirEntry[], Error>(__TAURI_INVOKE("list_dir", { path })),
	/**  Search file contents under `root` (WP 2.x). */
	search: (root: string, query: string, options: SearchOptions) => typedError<SearchHit[], Error>(__TAURI_INVOKE("search", { root, query, options })),
};

/** Events */
export const events = {
	externalChangeEvent: makeEvent<ExternalChangeEvent>("external-change-event"),
};

/* Types */
/**  A leaf block as the frontend flattens it (design 7.3). */
export type Block = {
	kind: string,
	text: string,
	from: number,
	to: number,
};

export type BlockOp = { op: "equal"; old: number; new: number } | { op: "changed"; old: number; new: number } | { op: "moved"; old: number; new: number } | { op: "inserted"; new: number } | { op: "deleted"; old: number };

/**  A hunk both sides changed, for the frontend to render as a conflict. */
export type Conflict = {
	from: number,
	to: number,
	ours: string,
	theirs: string,
};

export type DirEntry = {
	path: string,
	name: string,
	is_dir: boolean,
	byte_len: number,
	modified_ms: number | null,
};

/**  A document as read from disk. */
export type Document = {
	/**
	 *  The decoded content. For UTF-8 files this is the file's bytes minus the
	 *  BOM, with line endings untouched; the editor normalizes them itself.
	 */
	content: string,
	meta: DocumentMeta,
};

/**  Metadata about a document on disk. */
export type DocumentMeta = {
	path: string,
	/**  Size on disk in bytes. */
	byte_len: number,
	/**
	 *  Last modification time in milliseconds since the Unix epoch, when the
	 *  filesystem reports one.
	 */
	modified_ms: number | null,
	/**  BLAKE3 of the bytes on disk, hex. The token a save must present. */
	hash: string,
	/**
	 *  True for a file that is not UTF-8: it was decoded for display and
	 *  cannot be saved until converted.
	 */
	read_only: boolean,
	format: FileFormat,
};

/**  One line ending style. */
export type Eol = "lf" | "crlf" | "cr";

/**  Errors, serializable so the frontend can branch on `kind`. */
export type Error = { kind: "not_implemented"; command: string } | { kind: "read"; path: string; message: string } | { kind: "write"; path: string; message: string } | { kind: "hash_mismatch"; path: string; expected: string; actual: string } | { kind: "read_only_encoding"; path: string; encoding: string };

/**  Payload of the `external_change` event (design 6.4). */
export type ExternalChange = {
	path: string,
	content: string,
	hash: string,
	/**
	 *  Edits from the last known disk content to `content`, so the frontend
	 *  applies one transaction and cursor, scroll, and undo map through.
	 */
	changes: PositionEdit[],
};

/**  The watcher's report of a write by another process (design 6.4). */
export type ExternalChangeEvent = ExternalChange;

/**
 *  How a file is stored, so a save can restore it. Returned on open and
 *  passed back on save; the app may change fields the user asked to change.
 */
export type FileFormat = {
	/**  Dominant line ending, used for new lines. */
	eol: Eol,
	/**  True when the file mixes endings; existing lines keep theirs on save. */
	mixed_eol: boolean,
	bom: boolean,
	/**  True when the file ended with a line terminator. */
	trailing_newline: boolean,
	/**  Encoding label from `encoding_rs`; only `utf-8` documents can be saved. */
	encoding: string,
};

export type MergeResult = {
	changes: PositionEdit[],
	conflicts: Conflict[],
};

/**  One position-based edit the frontend applies as a CodeMirror change. */
export type PositionEdit = {
	/**  UTF-16 offsets into the document the edit applies to. */
	from: number,
	to: number,
	insert: string,
};

/**  What a successful save reports back. */
export type SaveResult = {
	hash: string,
	byte_len: number,
	modified_ms: number | null,
};

export type SearchHit = {
	path: string,
	line: number,
	from: number,
	to: number,
	text: string,
};

export type SearchOptions = {
	case_sensitive: boolean,
	regex: boolean,
	max_results: number,
};

/**  Who wrote a snapshot. */
export type SnapshotAuthor = "user" | "external" | "agent";

export type SnapshotInfo = {
	id: string,
	path: string,
	author: SnapshotAuthor,
	timestamp_ms: number,
	hash: string,
	byte_len: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

