// Generated by crates/app. Do not edit; run `cargo run -p markdown-app --bin export-bindings`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Read a document for a window: its bytes, the version it was found in,
	 *  and a watch on it.
	 * 
	 *  Three things that all need the file, done where the file is. Asking
	 *  for them afterwards meant the window sending every document back
	 *  across the bridge to say what this side had just read, and the
	 *  watcher reading each one a second time — which on a session of two
	 *  hundred tabs was two hundred files read twice and five megabytes sent
	 *  nowhere (plan WP 3.3). It also closed a gap: a writer landing between
	 *  the read and the watch used to leave the window holding one version
	 *  and the watcher calling the next one the baseline.
	 * 
	 *  Neither the record nor the watch is a reason to refuse a file, so
	 *  both failures are dropped rather than returned. A file too large to
	 *  edit is not recorded at all: nothing in the app can change it, so
	 *  there would never be a second version for the first to be compared
	 *  with, and storing it would double what a very large file costs.
	 */
	openDocument: (path: string) => typedError<Document, Error>(__TAURI_INVOKE("open_document", { path })),
	/**
	 *  Save the buffer in the file's stored form, refusing when the file on
	 *  disk no longer matches `expected_hash`.
	 */
	saveDocument: (path: string, content: string, expectedHash: string | null, format: FileFormat) => typedError<SaveResult, Error>(__TAURI_INVOKE("save_document", { path, content, expectedHash, format })),
	/**  Rewrite a non-UTF-8 file as UTF-8 and return it freshly read. */
	convertDocumentToUtf8: (path: string) => typedError<Document, Error>(__TAURI_INVOKE("convert_document_to_utf8", { path })),
	/**
	 *  Let the webview load images from a document's folder and below.
	 * 
	 *  The asset protocol starts with an empty scope (design 8), and it grows
	 *  only here and in `open_pdf`, only to the folder of a file the reader
	 *  has opened. Nothing else in the app can widen it, and nothing outside
	 *  those folders is reachable from the page.
	 */
	allowDocumentImages: (path: string) => typedError<null, Error>(__TAURI_INVOKE("allow_document_images", { path })),
	/**
	 *  Take charge of a PDF, without reading a byte of it (ADR 0035).
	 * 
	 *  The two things the webview cannot ask, in one round trip: whether the
	 *  file is there and small enough to take on, and — the answer being yes
	 *  — permission to read it. The scope call is what `open_document` gets
	 *  on the way past, and a PDF never goes through `open_document`, so it
	 *  has to be asked for here or the asset protocol answers 403 and the
	 *  pane stays blank.
	 */
	openPdf: (path: string) => typedError<PdfInfo, Error>(__TAURI_INVOKE("open_pdf", { path })),
	/**
	 *  Store an image pasted into a document, beside it in `assets`.
	 * 
	 *  The bytes arrive base64-encoded because that is one string across the
	 *  bridge; the alternative the generated bindings would give us is a JSON
	 *  array of a million numbers for every screenshot.
	 */
	writeAsset: (document: string, name: string, data: string) => typedError<AssetWrite, Error>(__TAURI_INVOKE("write_asset", { document, name, data })),
	/**
	 *  Store an image dropped onto a document. The same gesture, arriving as
	 *  a path rather than as bytes, so the file is copied and never crosses
	 *  the bridge at all.
	 */
	importAsset: (document: string, source: string) => typedError<AssetWrite, Error>(__TAURI_INVOKE("import_asset", { document, source })),
	/**
	 *  Write a rendered document out as a page of its own (plan WP 3.2).
	 * 
	 *  The page arrives already rendered -- the markdown renderer is the
	 *  frontend's, and what it produces is what Read mode shows -- with a
	 *  numbered sentinel where each local image goes. What this adds is the
	 *  images, which are dealt with here because the bytes are here.
	 * 
	 *  An image outside the folders the asset protocol has been opened to is
	 *  not read. Read mode could not have shown it either, and an export is
	 *  not a way around the fence design 8 puts around a document's folder;
	 *  the page names it and does not carry it, which is what a missing
	 *  image already looks like.
	 */
	exportHtml: (path: string, html: string, images: string[]) => typedError<ExportWrite, Error>(__TAURI_INVOKE("export_html", { path, html, images })),
	/**  Watch a file for writes by other processes. */
	watch: (path: string) => typedError<null, Error>(__TAURI_INVOKE("watch", { path })),
	/**  Stop watching a file. */
	unwatch: (path: string) => typedError<null, Error>(__TAURI_INVOKE("unwatch", { path })),
	/**
	 *  Three-way merge of an external write into a dirty buffer (design 7.2).
	 * 
	 *  The one command with no failure to report: three strings always have
	 *  a merge, even when every hunk of it is a conflict.
	 */
	merge3: (base: string, ours: string, theirs: string) => __TAURI_INVOKE<MergeResult>("merge3", { base, ours, theirs }),
	/**  Store a snapshot of `content` for `path`. */
	snapshot: (path: string, content: string, author: SnapshotAuthor) => typedError<SnapshotInfo, Error>(__TAURI_INVOKE("snapshot", { path, content, author })),
	/**  List the snapshots stored for `path`, newest first. */
	listSnapshots: (path: string) => typedError<SnapshotInfo[], Error>(__TAURI_INVOKE("list_snapshots", { path })),
	/**  Read one snapshot's content. */
	readSnapshot: (id: string) => typedError<string, Error>(__TAURI_INVOKE("read_snapshot", { id })),
	/**
	 *  What this window looked like when it was last open, plus the
	 *  preferences and the recent files (design 4.1).
	 * 
	 *  One round trip, because a window needs all three before it draws.
	 */
	loadWindow: () => __TAURI_INVOKE<Restore>("load_window"),
	/**
	 *  Record what this window holds.
	 * 
	 *  This is both halves of design 6.5: what the next launch puts back,
	 *  and the registry that decides which window a file the OS hands us
	 *  belongs to. The value is current the moment this returns; only the
	 *  write to disk waits for the store's interval.
	 */
	saveWindow: (content: WindowContent, recents: string[]) => __TAURI_INVOKE<void>("save_window", { content, recents }),
	/**
	 *  Change the preferences.
	 * 
	 *  The preferences are the app's, not a window's, so every window is
	 *  told: the reader who picks a theme in one of them has picked it for
	 *  all of them, and a second window still wearing the old one would be
	 *  the app disagreeing with itself (plan WP 2.6). The window that asked
	 *  hears it too, and applying what it already applied costs nothing.
	 */
	saveSettings: (settings: Settings) => __TAURI_INVOKE<void>("save_settings", { settings }),
	/**
	 *  Write the settings and the session now, rather than at the next
	 *  interval. What a window does before it closes.
	 */
	flushState: () => typedError<null, Error>(__TAURI_INVOKE("flush_state")),
	/**
	 *  Files the OS asked this window to open before it was listening.
	 * 
	 *  Draining the queue is also how a window says it is ready: from here
	 *  on the same files arrive as an event instead of waiting, which is
	 *  what keeps a launch argument from being lost to a listener that was
	 *  not attached yet, and from being opened twice by one that was.
	 */
	takeLaunchPaths: () => __TAURI_INVOKE<string[]>("take_launch_paths"),
	/**  The window has finished what it wanted to do before closing. */
	confirmClose: () => __TAURI_INVOKE<void>("confirm_close"),
	/**
	 *  Align two block lists for the semantic diff (design 7.3, plan WP 2.2).
	 * 
	 *  The frontend sends the middle: the blocks the two sides already agree
	 *  on at each end are matched off there, where the saving is in what
	 *  never crosses the bridge.
	 * 
	 *  It cannot fail. Both sides arrive as arguments, so there is nothing
	 *  to read, nothing to lock, and no answer but the alignment of what
	 *  was sent.
	 */
	blockDiff: (oldBlocks: Block[], newBlocks: Block[]) => __TAURI_INVOKE<BlockOp[]>("block_diff", { oldBlocks, newBlocks }),
	/**
	 *  Open a second window (design 4.1, Cmd+Shift+N).
	 * 
	 *  It comes up over the one that asked for it and the same size, which
	 *  is where the reader is looking; it starts empty, because a new window
	 *  is somewhere to put something, not a copy of what is already open.
	 */
	newWindow: () => typedError<string, Error>(__TAURI_INVOKE("new_window")),
	/**
	 *  Hand a tab to another window (design 6.5, plan WP 2.5).
	 * 
	 *  `dropped` says the tab was let go of with the pointer, and then where
	 *  the pointer is decides: a window under it takes the tab in, and
	 *  nothing under it tears the tab into a new window there. Without it —
	 *  the command rather than the drag — it is always a new window, over
	 *  the one the tab came from.
	 * 
	 *  The pointer is read here rather than sent from the webview. A drag
	 *  that has left the window is no longer something the webview can
	 *  measure: what `WebKit` reports as the end of one is a point near where
	 *  the reader let go and not the point itself, which was out by fifty
	 *  pixels in both directions when this was measured. The window manager
	 *  knows where the pointer is, in the same coordinates a window frame is
	 *  in, on whichever monitor it is over.
	 * 
	 *  A document cannot be in two windows at once, because a document lives
	 *  in a webview and two webviews share nothing. So this is a move and
	 *  not a copy: what is answered here is what the window it left is
	 *  waiting for before it lets go.
	 */
	moveTab: (tab: TabMove, dropped: boolean) => typedError<TabMoved, Error>(__TAURI_INVOKE("move_tab", { tab, dropped })),
	/**
	 *  Tabs another window handed this one before it was listening.
	 * 
	 *  Draining is also how a window says it is ready, exactly as
	 *  `take_launch_paths` is: from here on a tab reaches it as an event.
	 */
	takeMovedTabs: () => __TAURI_INVOKE<TabMove[]>("take_moved_tabs"),
	/**
	 *  Whether another window already has this file open, and if so, bring
	 *  it forward with the file in front (design 6.5).
	 * 
	 *  One document belongs to one window, so a file the reader opens from
	 *  anywhere — the palette, the open panel, the tree — goes to the window
	 *  that already has it rather than being opened a second time. The
	 *  session is the registry that answers this, as it is for a file the OS
	 *  hands us (WP 1.8), so the answer is only as fresh as the last thing a
	 *  window said about itself; opening one file in two windows in the same
	 *  instant opens it twice.
	 */
	revealPath: (path: string) => __TAURI_INVOKE<boolean>("reveal_path", { path }),
	/**
	 *  Open a folder as this window's workspace (design 4.1).
	 * 
	 *  Answers with the root, which is the path every entry under it is
	 *  built from. The tree is not returned with it: the window asks for the
	 *  levels it shows, and the one it shows first is one `list_dir` away.
	 */
	openFolder: (path: string) => typedError<string, Error>(__TAURI_INVOKE("open_folder", { path })),
	/**
	 *  Let the folder go: the watch stops with it, and so does whatever it
	 *  was being searched for.
	 */
	closeFolder: () => __TAURI_INVOKE<void>("close_folder"),
	/**  One level of the folder tree, honouring `.gitignore`. */
	listDir: (path: string) => typedError<DirEntry[], Error>(__TAURI_INVOKE("list_dir", { path })),
	/**
	 *  The files in the open folder that match what has been typed into
	 *  Cmd+P, best first (plan WP 2.4).
	 * 
	 *  With no folder open there is nothing to match against and the window
	 *  is offering its tabs and its recents, which it ranks itself. That is
	 *  an empty answer rather than an error: a folder can be closed while a
	 *  keystroke is still crossing the bridge.
	 */
	findFiles: (query: string, limit: number) => __TAURI_INVOKE<FileMatches>("find_files", { query, limit }),
	/**
	 *  Start searching the open folder's contents under the window's own
	 *  number for it; results follow as events carrying that number.
	 * 
	 *  The pattern is compiled here rather than on the search thread, so a
	 *  regular expression with a typo in it comes back to the field it was
	 *  typed into instead of arriving later as a result that is not one.
	 */
	startSearch: (id: number, query: string, options: SearchOptions) => typedError<null, Error>(__TAURI_INVOKE("start_search", { id, query, options })),
	/**
	 *  Stop the search with this id, if it is still the one running.
	 * 
	 *  The id is checked so that a cancel arriving after the reader has
	 *  already started another search cannot stop the new one.
	 */
	cancelSearch: (id: number) => __TAURI_INVOKE<void>("cancel_search", { id }),
	/**  Make an empty file in `dir`, from the sidebar's "New file". */
	createFile: (dir: string, name: string) => typedError<string, Error>(__TAURI_INVOKE("create_file", { dir, name })),
	/**  Rename a file within its folder, from the sidebar's inline rename. */
	renamePath: (path: string, name: string) => typedError<string, Error>(__TAURI_INVOKE("rename_path", { path, name })),
	/**
	 *  What this document is read in, if the reader gave it settings of its
	 *  own (design 11). An answer of nothing means it follows the app.
	 */
	documentOverride: (path: string) => __TAURI_INVOKE<Override>("document_override", { path }),
	/**
	 *  Give this document its own reading settings, or take them away.
	 * 
	 *  Keyed by path in app data rather than written into the file: design
	 *  11's point is that the reader can set one report in a serif without
	 *  the file, or whoever reads it next, knowing anything about it.
	 */
	setDocumentOverride: (path: string, reading: Override) => __TAURI_INVOKE<Override>("set_document_override", { path, reading }),
	/**
	 *  A window's answer to one question the server asked it.
	 * 
	 *  An id nobody is waiting for is dropped rather than refused: that is
	 *  an answer that arrived after its question timed out, and there is
	 *  nothing left to give it to.
	 */
	answerAgent: (id: number, answer: AgentAnswer) => __TAURI_INVOKE<void>("answer_agent", { id, answer }),
	/**  What the status bar says about the agent server. */
	agentStatus: () => __TAURI_INVOKE<AgentStatus>("agent_status"),
	/**
	 *  A fresh token, for the reader who wants the old one to stop working.
	 * 
	 *  The server keeps running on the same port: only the token changes,
	 *  which is what every client configured with `--mcp-stdio` picks up on
	 *  its next connection, because that mode reads the file every time.
	 */
	rotateAgentToken: () => typedError<null, Error>(__TAURI_INVOKE("rotate_agent_token")),
	/**
	 *  The client configuration to paste, for the palette command that
	 *  copies one.
	 */
	agentClientConfig: () => typedError<string, Error>(__TAURI_INVOKE("agent_client_config")),
	/**
	 *  Draw the menu bar the window has described.
	 * 
	 *  On macOS the bar belongs to the application and not to a window, so
	 *  what it shows is the window in front's: each window sends its own when
	 *  it is given the keyboard, and a window that is not in front does not
	 *  send at all. Nothing here decides what is in it — see `menu`.
	 * 
	 *  A menu that cannot be built is said so and let go. It is the one part
	 *  of the app whose absence costs a reader nothing they cannot do another
	 *  way, and refusing to open would be the worse answer.
	 */
	setMenu: (sections: MenuSection[]) => __TAURI_INVOKE<void>("set_menu", { sections }),
};

/** Events */
export const events = {
	agentAskEvent: makeEvent<AgentAskEvent>("agent-ask-event"),
	agentStatusEvent: makeEvent<AgentStatusEvent>("agent-status-event"),
	beforeCloseEvent: makeEvent<BeforeCloseEvent>("before-close-event"),
	externalChangeEvent: makeEvent<ExternalChangeEvent>("external-change-event"),
	fileRemovedEvent: makeEvent<FileRemovedEvent>("file-removed-event"),
	fileRenamedEvent: makeEvent<FileRenamedEvent>("file-renamed-event"),
	folderChangedEvent: makeEvent<FolderChangedEvent>("folder-changed-event"),
	menuCommandEvent: makeEvent<MenuCommandEvent>("menu-command-event"),
	openPathsEvent: makeEvent<OpenPathsEvent>("open-paths-event"),
	searchDoneEvent: makeEvent<SearchDoneEvent>("search-done-event"),
	searchProgressEvent: makeEvent<SearchProgressEvent>("search-progress-event"),
	settingsChangedEvent: makeEvent<SettingsChangedEvent>("settings-changed-event"),
	tabArrivedEvent: makeEvent<TabArrivedEvent>("tab-arrived-event"),
};

/* Types */
/**  One annotation, as `list_annotations` returns it. */
export type AgentAnnotation = {
	mark: AnnotationMark,
	/**
	 *  The palette word a colour stands for, absent for a colour the
	 *  reader chose themselves and for every other mark.
	 */
	meaning: AnnotationKind | null,
	/**
	 *  The source under the mark, collapsed to one line. The source and
	 *  not a rendering of it: an agent reading `the **first** step` is
	 *  looking at what the file says, which is the point of the round
	 *  trip.
	 */
	anchor: string,
	/**  UTF-16 offsets of the marked span in the current buffer. */
	from: number,
	to: number,
	comment: AgentComment | null,
};

/**
 *  What one window answered.
 * 
 *  `Failed` is a real answer and not an error: a window that has since
 *  closed the tab knows something the server needs to hear, and the
 *  alternative is the server waiting out its timeout for it.
 */
export type AgentAnswer = { answer: "documents"; documents: AgentDocument[] } | { answer: "text"; text: string; dirty: boolean } | { answer: "annotations"; annotations: AgentAnnotation[] } | 
/**
 *  Both sides flattened into blocks. The window is the side that
 *  holds the parse trees; the alignment is Rust's, the same one the
 *  gutter and Review are drawn from (design 7.3).
 */
{ answer: "changes"; old: Block[]; new: Block[] } | 
/**  The tab is open. `name` is what it is called there. */
{ answer: "opened"; name: string } | { answer: "failed"; message: string };

/**
 *  One question on its way to a window, with the number its answer comes
 *  back under.
 */
export type AgentAsk = {
	id: number,
	request: AgentRequest,
};

/**  One question on its way to a window, from the MCP server. */
export type AgentAskEvent = AgentAsk;

/**  One `<!-- kind: text -->` as an agent reads it. */
export type AgentComment = {
	kind: AnnotationKind,
	text: string,
};

/**  One open document, as `list_documents` returns it. */
export type AgentDocument = {
	/**
	 *  Absent for a document that has never been saved, which an agent
	 *  can read but has no path to write to.
	 */
	path: string | null,
	/**  What the tab calls it. */
	name: string,
	/**
	 *  The buffer is ahead of the file. Under autosave this is true for
	 *  about a second after a keystroke and false the rest of the time.
	 */
	dirty: boolean,
	/**
	 *  Length of the buffer in bytes of UTF-8 — the buffer's, not the
	 *  file's, because the buffer is what the other tools return.
	 */
	byte_len: number,
	/**  Last modification time of the file, when there is a file. */
	modified_ms: number | null,
};

/**  What the server is asking one window. */
export type AgentRequest = 
/**  Every document this window has open. */
{ ask: "documents" } | 
/**  The buffer, which may be ahead of disk. */
{ ask: "read"; path: string } | { ask: "annotations"; path: string } | 
/**
 *  The semantic diff from `against` to the buffer. Rust reads the
 *  old version out of the history and sends the text, because the
 *  window has no way to open a snapshot of its own.
 */
{ ask: "changes"; path: string; against: string } | 
/**
 *  Open a tab on the file and bring it in front. The one request
 *  that is about a document the window does not have yet.
 */
{ ask: "open"; path: string };

/**  What the status bar says about the server (plan WP 3.1). */
export type AgentStatus = {
	/**
	 *  The port it is listening on. Zero when it did not start, which is
	 *  what the status bar reads as "off" rather than as a port.
	 */
	port: number,
	/**  Where a client is configured from. */
	endpoint: string | null,
	/**
	 *  How many MCP sessions are open right now.
	 * 
	 *  Exact the moment a request has been served, because a session
	 *  begins and ends on one. Late by up to the transport's own idle
	 *  timeout for a client that goes away without saying so.
	 */
	clients: number,
};

/**
 *  The server came up, went away, or something happened on it. What the
 *  status bar draws (plan WP 3.1); the app's rather than a window's, so
 *  every window hears it.
 */
export type AgentStatusEvent = AgentStatus;

/**
 *  The closed comment vocabulary of design 4.3. Closed is what makes the
 *  comments machine-readable, which is the whole point of them.
 */
export type AnnotationKind = "note" | "attention" | "question" | "remove" | "keep" | "rewrite";

/**  What the reader did to a span (design 4.3). */
export type AnnotationMark = "highlight" | "strikethrough" | "color" | 
/**
 *  A comment with no mark of its own, which is still something the
 *  reader said.
 */
"comment";

/**  Whether the window follows the system or was told which to be. */
export type Appearance = "system" | "light" | "dark";

/**  A stored image: where it landed, and the link the document gets. */
export type AssetWrite = {
	path: string,
	/**
	 *  Relative to the document's folder, with forward slashes, ready to
	 *  go between the parentheses of a markdown link.
	 */
	relative: string,
	/**  False when the bytes were already there under this name. */
	written: boolean,
};

/**
 *  The window is about to close. Write down whatever is not on disk yet,
 *  then call `confirm_close`.
 */
export type BeforeCloseEvent = {
	label: string,
};

/**  A leaf block as the frontend flattens it (design 7.3). */
export type Block = {
	kind: string,
	text: string,
	from: number,
	to: number,
};

/**
 *  One step of the alignment of two block lists (design 7.3).
 * 
 *  The whole alignment is returned, `Equal` included, because that is
 *  what makes it an alignment: a consumer can walk both sides in step
 *  and knows what became of every block. `old` and `new` are indices
 *  into the lists that were sent, which carry the source ranges.
 * 
 *  A block that moved is reported once, where it arrived. Reporting the
 *  place it left as a deletion as well would mark the reader's document
 *  in two places for one thing having happened.
 */
export type BlockOp = { op: "equal"; old: number; new: number } | { op: "changed"; old: number; new: number; words: WordRun[] } | { op: "moved"; old: number; new: number } | { op: "inserted"; new: number } | { op: "deleted"; old: number };

/**  A hunk both sides changed, for the frontend to render as a conflict. */
export type Conflict = {
	from: number,
	to: number,
	ours: string,
	theirs: string,
};

/**  A selection, in UTF-16 offsets like every other position on the IPC. */
export type Cursor = {
	anchor: number,
	head: number,
};

export type DirEntry = {
	path: string,
	name: string,
	is_dir: boolean,
	byte_len: number,
	modified_ms: number | null,
};

/**  A document as read from disk. */
export type Document = {
	/**
	 *  The decoded content. For UTF-8 files this is the file's bytes minus the
	 *  BOM, with line endings untouched; the editor normalizes them itself.
	 */
	content: string,
	meta: DocumentMeta,
};

/**  Metadata about a document on disk. */
export type DocumentMeta = {
	path: string,
	/**  Size on disk in bytes. */
	byte_len: number,
	/**
	 *  Last modification time in milliseconds since the Unix epoch, when the
	 *  filesystem reports one.
	 */
	modified_ms: number | null,
	/**  BLAKE3 of the bytes on disk, hex. The token a save must present. */
	hash: string,
	/**  Why this document cannot be edited, or `None` when it can be. */
	read_only: ReadOnly | null,
	format: FileFormat,
};

/**
 *  One open document. Exactly one of the two fields is set: a file is
 *  read again from disk on restore, an untitled document is carried in
 *  the session file because losing it would lose the only copy.
 */
export type DocumentState = {
	path?: string | null,
	untitled?: Untitled | null,
};

/**  One line ending style. */
export type Eol = "lf" | "crlf" | "cr";

/**  Errors, serializable so the frontend can branch on `kind`. */
export type Error = { kind: "not_implemented"; command: string } | { kind: "read"; path: string; message: string } | { kind: "write"; path: string; message: string } | { kind: "hash_mismatch"; path: string; expected: string; actual: string } | { kind: "read_only_encoding"; path: string; encoding: string } | { kind: "too_large"; path: string; byte_len: number; limit: number } | { kind: "unavailable"; what: string; message: string } | { kind: "bad_query"; query: string; message: string };

/**  What an export did, for the line the status bar shows. */
export type ExportWrite = {
	path: string,
	/**  True when the images travel inside the page. */
	embedded: boolean,
	/**  How many images the page carries or names. */
	images: number,
	/**
	 *  How many of them are named but not there: unreadable, or bytes
	 *  that are not an image this app recognises.
	 */
	missing: number,
	/**  Where the copies went, when they were copied. */
	folder: string | null,
};

/**  Payload of the `external_change` event (design 6.4). */
export type ExternalChange = {
	path: string,
	content: string,
	hash: string,
	/**
	 *  The agent that wrote it, by the name it gave, when the write came
	 *  in over MCP rather than from the watcher (design 9). Plain file
	 *  watching cannot tell us who wrote a file; this can, which is what
	 *  makes the change attributable in the gutter and in the history.
	 */
	agent: string | null,
	/**
	 *  Edits from the file as the watcher last read it to `content`.
	 * 
	 *  The shell does not apply these: it merges against its own base,
	 *  because a buffer and the file it was saved to are not always the
	 *  same string — saving restores the stored form, and a document
	 *  whose last newline the reader deleted sits on disk with one.
	 *  They are here for a writer that holds both sides itself, which is
	 *  the MCP path of Phase 3 (design 9).
	 */
	changes: PositionEdit[],
};

/**  The watcher's report of a write by another process (design 6.4). */
export type ExternalChangeEvent = ExternalChange;

/**  Which of the three bundled families the page is set in. */
export type Family = "sans" | "serif" | "mono";

/**
 *  How a file is stored, so a save can restore it. Returned on open and
 *  passed back on save; the app may change fields the user asked to change.
 */
export type FileFormat = {
	/**  Dominant line ending, used for new lines. */
	eol: Eol,
	/**  True when the file mixes endings; existing lines keep theirs on save. */
	mixed_eol: boolean,
	bom: boolean,
	/**  True when the file ended with a line terminator. */
	trailing_newline: boolean,
	/**  Encoding label from `encoding_rs`; only `utf-8` documents can be saved. */
	encoding: string,
};

/**
 *  One file Cmd+P is offering, with the part of its name the query
 *  matched so the palette can underline it (plan WP 2.4).
 */
export type FileHit = {
	path: string,
	name: string,
	/**  The folder it is in, relative to the root and empty at the root. */
	dir: string,
	/**  UTF-16 offsets into `name` that the query matched. */
	positions: number[],
};

/**  What one Cmd+P query came back with. */
export type FileMatches = {
	hits: FileHit[],
	/**  How many files the folder walk holds, matched or not. */
	files: number,
	/**
	 *  The walk stopped at its limit, so the folder holds files that
	 *  nothing here was matched against. The palette says so rather than
	 *  quietly leaving them out.
	 */
	truncated: boolean,
};

/**
 *  Payload of the `file_removed` event: a file with a tab open on it is
 *  no longer on disk. The buffer stays; the next save recreates the file.
 */
export type FileRemoved = {
	path: string,
};

/**  A watched file is no longer on disk. */
export type FileRemovedEvent = FileRemoved;

/**
 *  Payload of the `file_renamed` event: the document is the same, its
 *  name is not, so the tab follows it.
 */
export type FileRenamed = {
	from: string,
	to: string,
};

/**  A watched file was renamed. */
export type FileRenamedEvent = FileRenamed;

/**
 *  Payload of the `folder_changed` event: something under the open
 *  folder was written, and these are the folders whose listings may no
 *  longer be right.
 */
export type FolderChange = {
	root: string,
	dirs: string[],
};

/**  Something under the open folder was written (plan WP 2.4). */
export type FolderChangedEvent = FolderChange;

/**  A menu item was chosen in the window that has the keyboard. */
export type MenuCommandEvent = string;

/**  One line of a menu. */
export type MenuEntry = 
/**
 *  One of the app's own commands, by the id its registry knows it by.
 *  That id is what comes back when the item is chosen, so the window
 *  runs the command the same way the palette and a key run it.
 */
{ kind: "command"; id: string; title: string; 
/**  Tauri's accelerator spelling, absent for a command with no key. */
accelerator: string | null; enabled: boolean } | { kind: "standard"; role: MenuRole } | { kind: "separator" };

/**
 *  One of the standard items: what it does belongs to `AppKit` rather than
 *  to this app, so the window can only say where it goes.
 */
export type MenuRole = "about" | "services" | "hide" | "hide_others" | "show_all" | "quit" | "cut" | "copy" | "paste" | "select_all" | "minimize" | "zoom" | "fullscreen" | "bring_all_to_front";

/**  One menu of the bar, named as the registry's groups are named. */
export type MenuSection = {
	title: string,
	items: MenuEntry[],
};

export type MergeResult = {
	changes: PositionEdit[],
	conflicts: Conflict[],
};

/**
 *  Files the OS wants this window to open: a second launch, a Finder
 *  double-click, an `open` from a terminal.
 */
export type OpenPathsEvent = string[];

/**
 *  What one document was given to be read in, instead of what the app
 *  was told (design 11).
 * 
 *  Every field is optional, and an override says only what it changes:
 *  a reader who gave one report a serif has not also frozen its size at
 *  today's. Theme and appearance are not here on purpose — they dress
 *  the window, and a window whose toolbar changed colour as the reader
 *  moved between tabs would be answering a question nobody asked.
 */
export type Override = {
	paper?: Paper | null,
	family?: Family | null,
	size?: number | null,
	measure?: number | null,
};

/**
 *  The page's own background (design 11), which is a setting of its own
 *  rather than a consequence of light or dark: paper colour changes
 *  reading comfort more than most people expect.
 */
export type Paper = "white" | "cream" | 
/**  A yellow legal pad. */
"pad" | 
/**  The high-contrast one, dark in a light window as well as a dark. */
"black";

/**  What the shell learns about a PDF before it hands one to the renderer. */
export type PdfInfo = {
	byte_len: number,
};

/**  One position-based edit the frontend applies as a `CodeMirror` change. */
export type PositionEdit = {
	/**  UTF-16 offsets into the document the edit applies to. */
	from: number,
	to: number,
	insert: string,
};

/**  Why a document cannot be edited, for the one banner that says so. */
export type ReadOnly = 
/**  Not UTF-8. It was decoded to be read, and converting it is offered. */
"encoding" | 
/**  Over [`EDITABLE_BYTES`], so it opens in Read mode only. */
"size";

/**
 *  What a window asks for when it starts.
 * 
 *  One round trip: the tabs it had, the files it has been opening, and
 *  the preferences, all of which it needs before it draws anything.
 */
export type Restore = {
	/**
	 *  `None` on a first launch, and after a session file that would not
	 *  parse: both mean a window with nothing to put back.
	 */
	content: WindowContent | null,
	recents: string[],
	settings: Settings,
};

/**  What a successful save reports back. */
export type SaveResult = {
	hash: string,
	byte_len: number,
	modified_ms: number | null,
};

/**  Payload of the `search_done` event: that search is over, and why. */
export type SearchDone = {
	id: number,
	hits: number,
	/**  The result limit was reached; the folder holds more. */
	truncated: boolean,
	/**  Another search replaced this one before it finished. */
	cancelled: boolean,
};

/**  A content search has finished, been filled up, or been replaced. */
export type SearchDoneEvent = SearchDone;

/**  One line of one file that a search matched. */
export type SearchHit = {
	path: string,
	/**  One-based, the way an editor counts lines. */
	line: number,
	/**
	 *  UTF-16 offsets of the match within `text`, which is what the
	 *  results panel highlights.
	 */
	from: number,
	to: number,
	/**
	 *  Where the match is in the line itself, which is where the cursor
	 *  goes. Not the same as `from` when a very long line has been cut
	 *  down to what a row can show.
	 */
	column: number,
	/**  The line as a row shows it, cut around the match when it is long. */
	text: string,
};

export type SearchOptions = {
	case_sensitive: boolean,
	regex: boolean,
	max_results: number,
};

/**
 *  Payload of the `search_progress` event: some of what one search has
 *  found so far. Results are sent in batches as they arrive, so a panel
 *  fills while the walk is still going (plan WP 2.4).
 */
export type SearchProgress = {
	/**
	 *  Which search these belong to. A reader who types again while the
	 *  last one is still walking gets a new id, and the old one's
	 *  leftovers are recognized and dropped.
	 */
	id: number,
	hits: SearchHit[],
};

/**  Some of what a content search has found so far. */
export type SearchProgressEvent = SearchProgress;

/**  Preferences that outlive every window (design 11, design 6.6). */
export type Settings = {
	/**
	 *  Design 6.6: on, because the file on disk is the channel to the AI
	 *  and an unsaved buffer is a state the AI cannot see.
	 */
	autosave?: boolean,
	theme?: ThemeId,
	appearance?: Appearance,
	paper?: Paper,
	family?: Family,
	/**  Reading size in CSS pixels; one of [`SIZES`]. */
	size?: number,
	/**  Line length in characters, within [`MEASURE_RANGE`]. */
	measure?: number,
};

/**
 *  The preferences have changed, in this window or in another one
 *  (plan WP 2.6). They belong to the app, so they reach every window.
 */
export type SettingsChangedEvent = Settings;

/**
 *  Which of the sidebar's panels was showing (design 4.1, 4.4).
 * 
 *  `Files` is the folder tree, and the recent files when no folder is
 *  open; it is where a window with a folder starts. `Outline` is the
 *  default without one, because a window with one document open has
 *  nothing to put in a tree.
 */
export type SidebarPanel = "files" | "outline" | "history";

/**
 *  Who wrote a snapshot.
 * 
 *  `Autosave` is separate from `User` because it is the one author that
 *  writes on a timer rather than because somebody decided to: the history
 *  coalesces a run of those into one version, and never coalesces onto a
 *  version anybody asked for (design 6.6).
 */
export type SnapshotAuthor = "user" | "autosave" | "external" | "agent";

export type SnapshotInfo = {
	id: string,
	path: string,
	author: SnapshotAuthor,
	/**
	 *  The name the agent gave itself, for a version an agent wrote
	 *  (design 9). `None` for every other author, and for an agent write
	 *  from a build older than plan WP 3.1.
	 */
	agent: string | null,
	timestamp_ms: number,
	hash: string,
	byte_len: number,
};

/**  A tab another window has handed this one (plan WP 2.5). */
export type TabArrivedEvent = TabMove;

/**
 *  What a tab is showing. Settings open as a tab rather than a modal
 *  (plan WP 1.9) and a PDF is read by a different engine entirely
 *  (ADR 0035), so not every tab has a document behind it.
 */
export type TabKind = "document" | "settings" | "pdf";

/**  Which projection of a document a tab was showing (design 4.2). */
export type TabMode = "read" | "edit" | "source";

/**
 *  A tab on its way from one window to another (design 6.5, plan WP 2.5).
 * 
 *  Each window is its own webview, so a document cannot be shared
 *  between two of them: moving one moves it, with its view state and its
 *  undo history. This is everything the window taking it in needs to put
 *  back what left the other one.
 * 
 *  Rust is the courier and not a reader of this. `state` is the editor's
 *  own serialization — its buffer, its selection and its undo history —
 *  and only the window that wrote it knows its shape.
 * 
 *  Every field is required, unlike the session's: this never lives on
 *  disk to be read by a later version of the app, it is one running
 *  window handing something to another, and a field left out would be a
 *  window losing part of what it was given.
 */
export type TabMove = {
	path: string | null,
	/**
	 *  The name a document with no file answers to, so `Untitled 2`
	 *  stays `Untitled 2` on the other side.
	 */
	untitled_name: string | null,
	/**
	 *  What the file was when the window that had it last read or wrote
	 *  it: the hash a save must present, and the format it must keep.
	 */
	meta: DocumentMeta | null,
	/**
	 *  The buffer, in the clear. It is also inside `state`; carrying it
	 *  here as well is what makes a payload the editor cannot read a
	 *  document that has lost its undo history rather than a lost
	 *  document.
	 */
	text: string,
	/**
	 *  What the file held when the window last saw it, which is what the
	 *  dirty dot and a merge are both measured against.
	 */
	base: string,
	/**
	 *  What the reader has already looked at, so the Changes badge does
	 *  not clear itself because a tab changed windows (design 4.4).
	 */
	reviewed: string,
	state: string,
	mode: TabMode,
	pinned: boolean,
	anchor: number,
	/**
	 *  Where a PDF was scrolled: the page in front, one-based, and
	 *  `None` for every tab that is not one (ADR 0035). `anchor` above
	 *  it is a source offset and stays one; a PDF's document fields
	 *  travel empty, because the window taking it in opens the file
	 *  itself rather than being handed a buffer there is none of.
	 */
	page: number | null,
	folded: string[],
};

/**  Where a moved tab went. */
export type TabMoved = {
	label: string,
	/**
	 *  Whether the window was made for it, which is the difference
	 *  between a tab torn off and a tab handed over.
	 */
	created: boolean,
};

/**
 *  One tab: a view onto a document, with the state that is per view
 *  (design 6.5).
 */
export type TabState = {
	kind?: TabKind,
	/**
	 *  Index into the window's `documents`. Two tabs naming the same one
	 *  restore as two views of one buffer, sharing undo.
	 */
	document?: number,
	mode?: TabMode,
	pinned?: boolean,
	/**  The tab that was in front. The first one marked wins. */
	active?: boolean,
	selection?: Cursor,
	/**
	 *  Where the view was scrolled, as a source offset. A character
	 *  survives a change of window width; a pixel offset does not.
	 */
	anchor?: number,
	/**
	 *  Where a PDF was scrolled: the page in front, one-based, and
	 *  unset for every tab that is not one.
	 * 
	 *  Its own field rather than a second meaning for `anchor`, which is
	 *  documented above as a source offset and is read as one by
	 *  everything that touches it. A page number written there would be
	 *  the kind of shortcut that is still being explained two years
	 *  later (ADR 0035).
	 */
	page?: number | null,
	/**  Heading ids folded in Read mode. */
	folded?: string[],
};

/**
 *  Which of the four curated themes of design 11 the window is dressed
 *  in. The colours themselves are a JSON file per theme in the theme
 *  package; this is only which of them the reader picked.
 */
export type ThemeId = "one" | "slate" | "ink" | "grove";

/**  An untitled document: a buffer with nowhere else to be kept. */
export type Untitled = {
	name: string,
	text: string,
};

/**
 *  What a window's own webview knows about itself. The frontend owns
 *  every field; the label and the frame are the window manager's.
 */
export type WindowContent = {
	documents?: DocumentState[],
	tabs?: TabState[],
	/**
	 *  The folder this window had open (plan WP 2.4), which it opens
	 *  again on the next launch. A folder that has since been moved or
	 *  deleted is simply not there any more; the window opens without
	 *  one, and its tabs are unaffected.
	 */
	folder?: string | null,
	sidebar?: boolean,
	/**  Which panel the sidebar was showing (design 4.4). */
	panel?: SidebarPanel,
	/**  Whether Read mode was showing the comments it folds away (4.3). */
	comments?: boolean,
};

/**
 *  A run of words that differ inside a pair of blocks the diff matched
 *  (design 7.3 step 3), as offsets into each side's block text.
 * 
 *  The offsets are into the block's text and not into the document,
 *  because the text is the normalized form: the words of a rewrapped
 *  paragraph are in different places in the file and the same places in
 *  what it says. Reverting is a block at a time, which is what the
 *  block's own range is for.
 * 
 *  One side is empty where the run is only an insertion or only a
 *  deletion, and sits where the missing words would go.
 */
export type WordRun = {
	old_from: number,
	old_to: number,
	new_from: number,
	new_to: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

