//! Tauri command handlers and the IPC contract (design 6.4). Each command
//! is a thin adapter over `mdreader_core`; commands later work packages
//! implement are declared here as stubs so the generated bindings carry
//! the whole contract and cannot drift from it.

// Command arguments arrive owned from the IPC deserializer; borrowing them
// would only add a clone on the caller side.
#![allow(clippy::needless_pass_by_value)]

use std::path::{Path, PathBuf};

use mdreader_core::{
    Block, BlockOp, DirEntry, Document, Error, ExternalChange, FileFormat, MergeResult, SaveResult,
    SearchHit, SearchOptions, SnapshotAuthor, SnapshotInfo,
};
use specta_typescript::Typescript;
use tauri_specta::{Builder, Event, collect_commands, collect_events};

/// Read a document from disk and return its content and metadata.
#[tauri::command]
#[specta::specta]
fn open_document(path: PathBuf) -> Result<Document, Error> {
    mdreader_core::read_document(&path)
}

/// Save the buffer in the file's stored form, refusing when the file on
/// disk no longer matches `expected_hash`.
#[tauri::command]
#[specta::specta]
fn save_document(
    path: PathBuf,
    content: String,
    expected_hash: Option<String>,
    format: FileFormat,
) -> Result<SaveResult, Error> {
    mdreader_core::save_document(&path, &content, expected_hash.as_deref(), &format)
}

/// Rewrite a non-UTF-8 file as UTF-8 and return it freshly read.
#[tauri::command]
#[specta::specta]
fn convert_document_to_utf8(path: PathBuf) -> Result<Document, Error> {
    mdreader_core::convert_to_utf8(&path)
}

fn not_implemented<T>(command: &str) -> Result<T, Error> {
    Err(Error::NotImplemented {
        command: command.to_owned(),
    })
}

/// Start watching a file for external writes (WP 1.7).
#[tauri::command]
#[specta::specta]
fn watch(path: PathBuf) -> Result<(), Error> {
    let _ = path;
    not_implemented("watch")
}

/// Stop watching a file (WP 1.7).
#[tauri::command]
#[specta::specta]
fn unwatch(path: PathBuf) -> Result<(), Error> {
    let _ = path;
    not_implemented("unwatch")
}

/// Three-way merge of an external write into a dirty buffer (WP 1.7).
#[tauri::command]
#[specta::specta]
fn merge3(base: String, ours: String, theirs: String) -> Result<MergeResult, Error> {
    let _ = (base, ours, theirs);
    not_implemented("merge3")
}

/// Store a snapshot of `content` for `path` (WP 1.7).
#[tauri::command]
#[specta::specta]
fn snapshot(path: PathBuf, content: String, author: SnapshotAuthor) -> Result<SnapshotInfo, Error> {
    let _ = (path, content, author);
    not_implemented("snapshot")
}

/// List the snapshots stored for `path` (WP 1.7).
#[tauri::command]
#[specta::specta]
fn list_snapshots(path: PathBuf) -> Result<Vec<SnapshotInfo>, Error> {
    let _ = path;
    not_implemented("list_snapshots")
}

/// Read one snapshot's content (WP 1.7).
#[tauri::command]
#[specta::specta]
fn read_snapshot(id: String) -> Result<String, Error> {
    let _ = id;
    not_implemented("read_snapshot")
}

/// Align two block lists for the semantic diff (WP 2.x).
#[tauri::command]
#[specta::specta]
fn block_diff(old_blocks: Vec<Block>, new_blocks: Vec<Block>) -> Result<Vec<BlockOp>, Error> {
    let _ = (old_blocks, new_blocks);
    not_implemented("block_diff")
}

/// List a directory, honouring `.gitignore` (WP 2.x).
#[tauri::command]
#[specta::specta]
fn list_dir(path: PathBuf) -> Result<Vec<DirEntry>, Error> {
    let _ = path;
    not_implemented("list_dir")
}

/// Search file contents under `root` (WP 2.x).
#[tauri::command]
#[specta::specta]
fn search(root: PathBuf, query: String, options: SearchOptions) -> Result<Vec<SearchHit>, Error> {
    let _ = (root, query, options);
    not_implemented("search")
}

/// The watcher's report of a write by another process (design 6.4).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, specta::Type, Event)]
pub struct ExternalChangeEvent(pub ExternalChange);

/// Every command and event of the contract, in one place.
#[must_use]
pub fn ipc_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            open_document,
            save_document,
            convert_document_to_utf8,
            watch,
            unwatch,
            merge3,
            snapshot,
            list_snapshots,
            read_snapshot,
            block_diff,
            list_dir,
            search,
        ])
        .events(collect_events![ExternalChangeEvent])
}

/// The TypeScript export settings.
#[must_use]
pub fn typescript() -> Typescript {
    Typescript::default().header(
        "// Generated by crates/app. Do not edit; run `cargo run -p mdreader-app --bin export-bindings`.",
    )
}

/// Where the generated bindings live, relative to this crate.
#[must_use]
pub fn bindings_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packages/ipc/src/bindings.ts")
}

/// Write the bindings file.
///
/// # Errors
/// Fails when the export or the write fails.
pub fn export_bindings(to: &Path) -> Result<(), specta_typescript::Error> {
    ipc_builder().export(typescript(), to)
}

/// Build and run the application with the given generated context.
///
/// # Panics
/// Panics if the Tauri runtime fails to start.
pub fn run(context: tauri::Context) {
    let builder = ipc_builder();
    #[cfg(debug_assertions)]
    if let Err(e) = export_bindings(&bindings_path()) {
        eprintln!("could not export IPC bindings: {e}");
    }
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        // Links in Read mode open in the system browser; the webview never
        // navigates away from the app (design 6.2).
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(context)
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// CI guard: the committed bindings must match what the current
    /// contract generates. Regenerate with the `export-bindings` binary.
    #[test]
    fn committed_bindings_are_current() {
        let dir = std::env::temp_dir().join(format!("mdreader-bindings-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("temp dir");
        let fresh = dir.join("bindings.ts");
        export_bindings(&fresh).expect("export");
        let generated = std::fs::read_to_string(&fresh).expect("read fresh");
        let committed = std::fs::read_to_string(bindings_path()).unwrap_or_default();
        assert!(
            generated == committed,
            "packages/ipc/src/bindings.ts is stale; run `cargo run -p mdreader-app --bin export-bindings`"
        );
    }
}
