export {
  type ChangeKind,
  changeMarkers,
  changesField,
  type LineChange,
  lineChanges,
  setChanges,
} from './changes/index.ts';
export {
  type AnnotationEdit,
  applyColor,
  applyComment,
  applyHighlight,
  applyStrikethrough,
  blockCommentPos,
  colorEdit,
  commentEdit,
  commentText,
  highlightEdit,
  strikethroughEdit,
  toggleWrapEdit,
} from './commands/annotate.ts';
export { wrapBold, wrapSelection } from './commands/format.ts';
export {
  continuation,
  insertNewlineMarkdown,
  lineMarkup,
  newlinePlan,
} from './commands/newline.ts';
export {
  type AnchorRange,
  addProperty,
  blockWidgetsField,
  buildDecorations,
  type CommandTarget,
  CommentWidget,
  changedRegion,
  commentNotes,
  DiagramWidget,
  hoveredAnchor,
  ImageWidget,
  livePreview,
  MathWidget,
  markdownHighlightStyle,
  type PreviewDecorations,
  type PreviewOptions,
  PropertiesWidget,
  previewOptions,
  previewTheme,
  type RevealRange,
  revealRanges,
  setHoveredAnchor,
  setProperty,
  toggleTaskAt,
  type VisibleRange,
} from './preview/index.ts';
export {
  baseExtensions,
  createEditorState,
  type EditorMode,
  markdownKeymap,
  markdownSupport,
  type StateOptions,
  setModeEffect,
} from './state.ts';
export { createEditor, type Editor, type EditorOptions } from './view.ts';
