export {
  type ChangeKind,
  changeMarkers,
  changeRuns,
  changesField,
  type LineChange,
  nextChange,
  previousChange,
  setChanges,
} from './changes/index.ts';
export {
  type AnnotationEdit,
  applyColor,
  applyComment,
  applyHighlight,
  applyStrikethrough,
  blockCommentPos,
  colorEdit,
  commentEdit,
  commentText,
  highlightEdit,
  strikethroughEdit,
  toggleWrapEdit,
} from './commands/annotate.ts';
export type { Edit } from './commands/edit.ts';
export {
  applyBold,
  applyCode,
  applyItalic,
  applyLink,
  boldEdit,
  codeEdit,
  isUrl,
  italicEdit,
  linkEdit,
  markEdit,
} from './commands/format.ts';
export { deleteMarkerBackward, indentListItem, outdentListItem } from './commands/list.ts';
export {
  continuation,
  insertNewlineMarkdown,
  lineMarkup,
  newlinePlan,
} from './commands/newline.ts';
export {
  addConflicts,
  type ConflictRegion,
  conflictAt,
  conflictRegion,
  conflictState,
  conflicts,
  conflictsChanged,
  conflictsField,
  conflictWidgets,
  hasConflicts,
  keepMine,
  keepMineHere,
  nextConflict,
  resolveConflict,
  takeTheirs,
  takeTheirsHere,
} from './conflict/index.ts';
export {
  type AnchorRange,
  addProperty,
  blockWidgetsField,
  buildDecorations,
  type CommandTarget,
  CommentWidget,
  changedRegion,
  codeHighlightDark,
  codeHighlightLight,
  commentNotes,
  DiagramWidget,
  hoveredAnchor,
  ImageWidget,
  livePreview,
  MathWidget,
  markdownHighlightStyle,
  type PreviewDecorations,
  type PreviewOptions,
  PropertiesWidget,
  previewOptions,
  previewTheme,
  type RevealRange,
  revealRanges,
  setHoveredAnchor,
  setProperty,
  toggleTaskAt,
  type VisibleRange,
} from './preview/index.ts';
export {
  countMatches,
  findIsOpen,
  findNext,
  findPrevious,
  getSearchQuery,
  type MatchCount,
  replaceAll,
  replaceNext,
  SearchQuery,
  setFindOpen,
  setSearchQuery,
} from './search/index.ts';
export {
  baseExtensions,
  createEditorState,
  type EditorMode,
  editorKeys,
  markdownKeymap,
  markdownSupport,
  type StateOptions,
  setDarkEffect,
  setModeEffect,
} from './state.ts';
export { createEditor, type Editor, type EditorOptions } from './view.ts';
